version: '3'
services:
    app:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        volumes:
            - ./:/app
            - /app/quickstart/node_modules
        command: "node server.js"
        ports:
            - '8080:8080'
        environment:
            AUTH_META_URL: "meta config url"
            AUTH_CLIENT_ID: "client id"
            AUTH_CLIENT_SECRET: "client secret"
            OSDU_API_BASE_URL: "base OSDU url"
